fullnameOverride: api-gateway
replicaCount: 1
image:
  repository: landd/api-gateway
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 3000

env:
  MONGODB_URI: "mongodb://mongodb:27017/api-db"
  PORT: "3000"

secrets:
  JWT_SECRET: "your-jwt-secret-here"

