fullnameOverride: attendance-service
replicaCount: 1
image:
  repository: landd/attendance-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 3000

env:
  MONGODB_URI: "mongodb://mongodb:27017/attendance-db"
  PORT: "3000"

secrets:
  JWT_SECRET: "your-jwt-secret-here"

