# Default values for common components
database:
  name: mongodb
  image: mongo:latest
  port: 27017
  storageSize: 1Gi
  storageClassName: local-path

gateway:
  name: lnd-gateway
  namespace: istio-system
