# Dev environment values for common components
database:
  image: mongo:6.0
  storageSize: 2Gi
  storageClassName: nfs-dev
  nfs:
    server: 10.0.8.33
    path: /var/nfs/general/dev
gateway:
  namespace: ld-dev
