apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: landd-user-service-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/L-and-D-Management-System/l-and-d-main.git
    targetRevision: master
    path: helm/services/user-service
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ld-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true